### ISSUE TITLE
KeyError: u'auth_method' ... Fresh Install Of pynsot Client From pypi

### ISSUE THREAD

**Issue by narJH27** [dropbox/pynsot#143]
I did a fresh install of the `pynsot` client from pypi and followed the documentation (http://pynsot.readthedocs.io/en/latest/config.html#config-ref) to help setup the `.pynsotrc` file in my local dev environment. 

Any `nsot` command, such as `nsot networks list` or `nsot sites list` or `nsot attributes list`, etc, resulted in the following traceback:

```(venv) [nseshan@nseshan-dbx pynsot]$ nsot sites list
Traceback (most recent call last):
  File "/home/nseshan/src/pynsot/venv/bin/nsot", line 11, in <module>
    sys.exit(app())
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/pynsot/commands/cmd_sites.py", line 135, in list
    ctx.obj.list(data, display_fields=DISPLAY_FIELDS)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/pynsot/app.py", line 637, in list
    resource = self.resource
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/pynsot/app.py", line 143, in resource
    return self.api.get_resource(self.resource_name)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/pynsot/app.py", line 124, in api
    self._api = client.get_api_client(**self.client_args)
  File "/home/nseshan/src/pynsot/venv/local/lib/python2.7/site-packages/pynsot/client.py", line 365, in get_api_client
    auth_method = client_args.pop('auth_method')
KeyError: u'auth_method'```

Seems like a bug to me.

**Comment by narJH27** [comment]
Reported in error. Closing.
