### ISSUE TITLE
Networks Add Broken - pop() takes at most 1 argument

### ISSUE THREAD

**Issue by coxley** [dropbox/pynsot#46]
Looks like data is expected to be a dict, but may be getting a list?

```
Traceback (most recent call last):
  File "/home/codey/docs/envs/ipam/bin/nsot", line 11, in <module>
    sys.exit(app())
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/pynsot/commands/cmd_networks.py", line 106, in add
    ctx.obj.add(data)
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/pynsot/app.py", line 375, in add
    self.rebase(data)
  File "/home/codey/docs/envs/ipam/lib/python2.7/site-packages/pynsot/app.py", line 361, in rebase
    site_id = data.pop('site_id', None)
TypeError: pop() takes at most 1 argument (2 given)
```

**Comment by coxley** [comment]
pynsot==0.14.2

**Comment by coxley** [comment]
Can confirm, `data` is a list of a dicts, all of the attributes that were attempted to be imported. (bulk add)
