### ISSUE TITLE
NSOT cli attribute update to multi not working

### ISSUE THREAD

**Issue by jimb0ne** [dropbox/pynsot#52]
```
$ nsot attributes update -i 74 --multi
Traceback (most recent call last):
  File "/srv/dbops/tools/nsot", line 8, in <module>
    load_entry_point('pynsot==0.16', 'console_scripts', 'nsot')()
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/pynsot/commands/cmd_attributes.py", line 369, in update
    ctx.obj.update(data)
  File "/srv/pynsot/envs/pynsot/lib/python2.7/site-packages/pynsot/app.py", line 535, in update
    attr_action = data.pop('attr_action')
KeyError: u'attr_action'
```

**Comment by jimb0ne** [comment]
This also doesn't work in the API at the moment.

**Comment by jathanism** [comment]
Ah, this is related to a conflict with the ``--multi`` flag w/ device/networks objects for updating list-type attributes, and the ``--multi`` flag for enabling list-type functionality on an attribute object.
