### ISSUE TITLE
Listing 'sites' and 'changes' raises TypeError

### ISSUE THREAD

**Issue by coxley** [dropbox/pynsot#74]
```python
$ nsot sites list      
Traceback (most recent call last):
  File "/home/codey/docs/envs/nsot_sync/bin/nsot", line 9, in <module>
    load_entry_point('pynsot==0.18.1', 'console_scripts', 'nsot')()
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/pynsot/commands/cmd_sites.py", line 128, in list
    ctx.obj.list(data, display_fields=DISPLAY_FIELDS)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/pynsot/app.py", line 509, in list
    obj = self.get_single_object(data, resource)
  File "/home/codey/docs/envs/nsot_sync/lib/python2.7/site-packages/pynsot/app.py", line 445, in get_single_object
    for natural_key in natural_keys:
TypeError: 'NoneType' object is not iterable
```

**Comment by jathanism** [comment]
Dangit. And this would be why we exhaustively unit test. I know exactly what the problem is. Thanks for reporting it.

**Comment by coxley** [comment]
:+1:
